const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DBKEY='nutritrack_pwa_v2';
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const n=(v,d=0)=>Number.isFinite(+v)?+v:d;
const r=(v,d=0)=>Math.round(n(v)*10**d)/10**d;
const dateISO=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const today=()=>dateISO(new Date());

const FOOD_DB=[
['Egg, large','1 egg',72,6.3,.4,4.8,0,.2,71,'protein'],['Eggs, 3 large','3 eggs',216,18.9,1.2,14.4,0,.6,213,'protein'],['Egg whites','100 g',52,10.9,.7,.2,0,.7,166,'protein'],['Chicken breast, cooked','100 g',165,31,0,3.6,0,0,74,'protein'],['Chicken thigh, cooked','100 g',209,26,0,10.9,0,0,90,'protein'],['Chicken leg, roasted','1 medium',180,24,0,9,0,0,90,'protein'],['Turkey breast','100 g',135,30,0,1,0,0,55,'protein'],['Salmon, cooked','100 g',206,22,0,12,0,0,59,'protein'],['Tuna in water','100 g',116,26,0,1,0,0,50,'protein'],['Prawns, cooked','100 g',99,24,.2,.3,0,0,111,'protein'],['Cod, cooked','100 g',105,23,0,.9,0,0,78,'protein'],['Lean beef, cooked','100 g',217,26,0,12,0,0,72,'protein'],['Greek yogurt 0%','200 g',118,20,7.2,.8,0,7.2,72,'protein'],['Protein yogurt','200 g',145,20,13,1.5,0,10,120,'protein'],['Cottage cheese','200 g',164,23,6,4.6,0,5,650,'protein'],['Whey protein','1 scoop',120,24,3,2,1,2,120,'protein'],['Milk, semi-skimmed','250 ml',118,8.5,12,4.2,0,12,105,''],
['White rice, cooked','100 g',130,2.7,28,.3,.4,.1,1,''],['Basmati rice, cooked','100 g',121,3.5,25.2,.4,.4,.1,1,''],['Brown rice, cooked','100 g',123,2.7,25.6,1,1.6,.2,4,''],['Oats, dry','40 g',152,5.1,27,2.8,4,.4,1,''],['Wholemeal bread','1 slice',90,4,15,1.5,2.5,1.5,180,''],['Potato, boiled','200 g',174,3.8,40,.2,3.6,1.8,12,''],['Sweet potato, baked','200 g',180,4,41,.3,6.6,13,72,''],['Pasta, cooked','100 g',157,5.8,31,.9,1.8,.6,1,''],['Quinoa, cooked','100 g',120,4.4,21.3,1.9,2.8,.9,7,''],
['Banana, medium','1',105,1.3,27,.4,3.1,14.4,1,''],['Apple, large','1',116,.6,31,.4,5.4,23,2,''],['Orange, medium','1',62,1.2,15.4,.2,3.1,12.2,0,''],['Blueberries','100 g',57,.7,14.5,.3,2.4,10,1,''],['Strawberries','100 g',32,.7,7.7,.3,2,4.9,1,''],['Avocado','100 g',160,2,8.5,14.7,6.7,.7,7,''],['Broccoli','100 g',35,2.4,7.2,.4,3.3,1.4,41,''],['Mixed salad','150 g',55,2.5,9,1,4.5,4,80,''],['Spinach','100 g',23,2.9,3.6,.4,2.2,.4,79,''],['Carrots','100 g',41,.9,9.6,.2,2.8,4.7,69,''],
['Almonds','30 g',174,6.4,6.1,15,3.5,1.2,0,''],['Peanuts','30 g',170,7.5,4.8,14.5,2.5,1.3,3,''],['Peanut butter','1 tbsp',94,3.6,3.2,8,1,1.5,74,''],['Olive oil','1 tbsp',119,0,0,13.5,0,0,0,''],['Cheddar cheese','30 g',121,7.5,.4,10,0,.1,186,''],
['Idli','1 medium',58,2,12,.4,.5,.2,150,'indian'],['Dosa, plain','1 medium',168,4,29,4,1.5,1,210,'indian'],['Masala dosa','1 medium',387,9,58,13,5,4,620,'indian'],['Appam','1 medium',120,2,24,2,1,2,100,'indian'],['Puttu','1 cup',290,6,60,3,5,2,210,'indian'],['Idiyappam','2 pieces',180,4,38,1,2,1,160,'indian'],['Kerala parotta','1',260,6,38,9,2,2,420,'indian'],['Chapati','1 medium',120,3.5,20,3.7,3,1,190,'indian'],['Naan, plain','1 medium',262,8.7,45.4,5.1,2.2,3.2,418,'indian'],['Upma','1 cup',250,6,45,6,5,4,400,'indian'],['Poha','1 cup',250,6,45,6,4,3,380,'indian'],['Sambar','1 cup',160,8,24,4,7,5,520,'indian'],['Rasam','1 cup',75,2,12,2,2,3,500,'indian'],['Coconut chutney','2 tbsp',90,1.5,4,8,2,1,160,'indian'],['Lentils / dal, cooked','1 cup',230,18,40,.8,15.6,3.6,4,'indian protein'],['Chickpeas, cooked','1 cup',269,14.5,45,4.3,12.5,7.9,11,'indian protein'],['Rajma','1 cup',245,15,44,2,13,5,510,'indian protein'],['Paneer','100 g',265,18,6,21,0,3,22,'indian protein'],['Paneer curry','1 cup',360,18,18,24,4,6,720,'indian protein'],['Chicken curry, Kerala style','1 cup',290,28,10,15,2,4,690,'indian protein'],['Chicken biryani','1 plate',620,32,78,20,4,5,980,'indian'],['Beef curry, Kerala style','1 cup',320,28,10,19,2,4,680,'indian protein'],['Beef fry, Kerala style','100 g',310,28,7,19,2,2,590,'indian protein'],['Fish curry, Kerala style','1 cup',220,24,8,10,2,3,620,'indian protein'],['Fish fry','1 medium fillet',240,26,7,12,1,1,480,'indian protein'],['Egg curry','2 eggs + gravy',290,15,12,20,2,5,620,'indian protein'],['Vegetable thoran','1 cup',180,5,18,11,7,5,300,'indian'],['Avial','1 cup',220,6,25,12,7,8,420,'indian'],['Olan','1 cup',160,4,20,8,6,5,310,'indian'],['Kerala red rice, cooked','1 cup',220,5,47,1.5,3,1,4,'indian'],['Curd rice','1 cup',280,8,47,7,2,7,450,'indian'],['Lemon rice','1 cup',310,6,54,8,3,3,500,'indian'],['Ghee rice','1 cup',360,6,56,13,2,2,430,'indian'],['Kappa / tapioca, boiled','200 g',320,2.8,76,.6,3.6,3.4,20,'indian'],['Kappa biryani','1 plate',650,27,82,24,7,6,1000,'indian'],['Banana chips','30 g',160,1,18,10,2,5,120,'indian'],['Pazham pori','1 piece',210,2,34,8,2,15,120,'indian'],['Vada','1 medium',170,5,20,8,4,2,300,'indian'],['Samosa','1 medium',262,5,32,13,3,3,420,'indian'],['Tea with milk','1 cup',45,1.5,6,1.5,0,6,35,'indian'],['Coffee with milk','1 cup',55,2,7,2,0,7,45,'']
].map((x,i)=>({id:'db'+i,name:x[0],serving:x[1],cal:x[2],protein:x[3],carbs:x[4],fat:x[5],fibre:x[6],sugar:x[7],sodium:x[8],tags:x[9]}));

function defaults(){return{profile:{name:'Me',sex:'male',age:30,height:175,weight:80,activity:1.375,goal:-250,protein:130,fibre:30,times:{Breakfast:'08:00',Lunch:'13:00',Dinner:'19:00',Snack:'16:00'}},foods:[],body:[],favorites:[],recent:[]}}
let state=load();let foodFilter='all';let dialogFood=null;let deferredInstall=null;
function load(){try{const v=JSON.parse(localStorage.getItem(DBKEY)||'null');return v?{...defaults(),...v,profile:{...defaults().profile,...v.profile,times:{...defaults().profile.times,...(v.profile?.times||{})}}}:defaults()}catch{return defaults()}}
function save(){localStorage.setItem(DBKEY,JSON.stringify(state))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1600)}
function navigate(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='trends')setTimeout(renderTrends,30)}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
function targets(){const p=state.profile;const bmr=10*n(p.weight)+6.25*n(p.height)-5*n(p.age)+(p.sex==='male'?5:-161);const cal=Math.max(1200,Math.round(bmr*n(p.activity)+n(p.goal)));const protein=Math.max(40,n(p.protein,130));const fat=Math.round(cal*.28/9);const carbs=Math.max(50,Math.round((cal-protein*4-fat*9)/4));return{cal,protein,carbs,fat,fibre:Math.max(15,n(p.fibre,30)),sugar:Math.round(cal*.025/4),sodium:2300}}
function totals(date){return state.foods.filter(x=>x.date===date).reduce((a,x)=>{['cal','protein','carbs','fat','fibre','sugar','sodium'].forEach(k=>a[k]+=n(x[k]));return a},{cal:0,protein:0,carbs:0,fat:0,fibre:0,sugar:0,sodium:0})}
function pct(v,t){return Math.max(0,Math.min(100,t?v/t*100:0))}
function mealTime(m){return state.profile.times[m]||''}
function selectedDate(){return $('#selectedDate').value||today()}
function renderHome(){const d=selectedDate(),t=totals(d),g=targets();const rem=Math.round(g.cal-t.cal);$('#calRemaining').textContent=Math.abs(rem);$('#calRemaining').parentElement.querySelector('span').textContent=rem>=0?'kcal left':'kcal over';$('#calConsumed').textContent=`${Math.round(t.cal)} kcal`;$('#calTargetText').textContent=`of ${g.cal} kcal target`;$('#calRing').style.strokeDashoffset=(314.16*(1-pct(t.cal,g.cal)/100)).toFixed(2);$('#calRing').style.stroke=rem<0?'#e11d48':'#14b8a6';
 const macros=[['Protein',t.protein,g.protein,'g'],['Carbs',t.carbs,g.carbs,'g'],['Fat',t.fat,g.fat,'g']];$('#macroGrid').innerHTML=macros.map(([a,b,c,u])=>`<div class="macro-card"><span class="muted">${a}</span><strong>${r(b)}${u}</strong><div class="mini-bar"><i style="width:${pct(b,c)}%"></i></div><small class="muted">${r(c)}${u} target</small></div>`).join('');
 const meals=['Breakfast','Lunch','Dinner','Snack'];$('#mealSummary').innerHTML=meals.map(m=>{const items=state.foods.filter(x=>x.date===d&&x.meal===m);const c=items.reduce((s,x)=>s+n(x.cal),0);return`<div class="meal-row"><div><strong>${m}</strong><div class="meal-meta">${mealTime(m)} · ${items.length?items.length+' item'+(items.length>1?'s':''):'Nothing logged'}</div></div><strong>${Math.round(c)} kcal</strong></div>`}).join('');
 const last=[...state.body].sort((a,b)=>b.date.localeCompare(a.date))[0];$('#bodySummary').innerHTML=last?`<div class="history-row"><div><strong>${last.weight??'—'} kg</strong><div class="row-meta">${last.date}${last.fat?` · Body fat ${last.fat}%`:''}</div></div><span class="pill">Latest</span></div>`:'No body measurements yet.'}
function renderFoodResults(){const q=$('#foodSearch').value.trim().toLowerCase();let arr=FOOD_DB.filter(f=>!q||f.name.toLowerCase().includes(q)||f.serving.toLowerCase().includes(q));if(foodFilter==='indian')arr=arr.filter(f=>f.tags.includes('indian'));if(foodFilter==='protein')arr=arr.filter(f=>f.tags.includes('protein')||f.protein>=15);if(foodFilter==='fav')arr=arr.filter(f=>state.favorites.includes(f.id));if(foodFilter==='recent'){const rank=new Map(state.recent.map((x,i)=>[x,i]));arr=arr.filter(f=>rank.has(f.id)).sort((a,b)=>rank.get(a.id)-rank.get(b.id))}arr=arr.slice(0,50);$('#foodResults').innerHTML=arr.length?arr.map(f=>`<div class="food-result"><div><div class="title">${state.favorites.includes(f.id)?'<span class="star">★</span> ':''}${f.name}</div><div class="nutrition">${f.serving} · ${f.cal} kcal · P ${f.protein}g · C ${f.carbs}g · F ${f.fat}g</div></div><button class="add-btn" data-food="${f.id}">Add</button></div>`).join(''):'<div class="empty-copy">No matching foods. Use Manual / custom food below.</div>';$$('[data-food]').forEach(b=>b.onclick=()=>openFoodDialog(b.dataset.food))}
function openFoodDialog(fid){dialogFood=FOOD_DB.find(f=>f.id===fid);if(!dialogFood)return;$('#dialogFoodName').textContent=dialogFood.name;$('#dialogBaseServing').textContent='Base serving: '+dialogFood.serving;$('#dialogQty').value=1;renderDialogNutrition();$('#toggleFav').textContent=(state.favorites.includes(fid)?'★ Favourited':'♡ Favourite');$('#foodDialog').showModal()}
function renderDialogNutrition(){if(!dialogFood)return;const q=Math.max(.1,n($('#dialogQty').value,1));$('#dialogNutrition').innerHTML=[['Calories',dialogFood.cal*q,'kcal'],['Protein',dialogFood.protein*q,'g'],['Carbs',dialogFood.carbs*q,'g'],['Fat',dialogFood.fat*q,'g']].map(([a,b,u])=>`<div><b>${r(b,1)} ${u}</b><span>${a}</span></div>`).join('')}
$('#dialogQty').addEventListener('input',renderDialogNutrition);$('#confirmFood').onclick=()=>{if(!dialogFood)return;const q=Math.max(.1,n($('#dialogQty').value,1));const item={...dialogFood,id:id(),sourceId:dialogFood.id,date:$('#foodDate').value,meal:$('#foodMeal').value,serving:`${q} × ${dialogFood.serving}`,cal:dialogFood.cal*q,protein:dialogFood.protein*q,carbs:dialogFood.carbs*q,fat:dialogFood.fat*q,fibre:dialogFood.fibre*q,sugar:dialogFood.sugar*q,sodium:dialogFood.sodium*q,created:Date.now()};delete item.tags;state.foods.push(item);state.recent=[dialogFood.id,...state.recent.filter(x=>x!==dialogFood.id)].slice(0,20);save();$('#foodDialog').close();renderAll();toast('Food added')};$('#toggleFav').onclick=()=>{if(!dialogFood)return;const f=dialogFood.id;state.favorites=state.favorites.includes(f)?state.favorites.filter(x=>x!==f):[f,...state.favorites];save();$('#toggleFav').textContent=(state.favorites.includes(f)?'★ Favourited':'♡ Favourite');renderFoodResults()};
$$('#foodFilterChips .chip').forEach(b=>b.onclick=()=>{$$('#foodFilterChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');foodFilter=b.dataset.filter;renderFoodResults()});$('#foodSearch').addEventListener('input',renderFoodResults);
function renderFoodLog(){const d=$('#foodDate').value||today(),arr=state.foods.filter(x=>x.date===d).sort((a,b)=>(a.created||0)-(b.created||0)),t=totals(d);$('#logTotal').textContent=`${Math.round(t.cal)} kcal`;$('#foodLog').innerHTML=arr.length?arr.map(x=>`<div class="log-row"><div><strong>${x.name}</strong><div class="row-meta">${x.meal} · ${x.serving||''} · P ${r(x.protein,1)}g</div></div><div class="row-actions"><strong>${Math.round(x.cal)} kcal</strong> <button class="delete-mini" data-del-food="${x.id}">×</button></div></div>`).join(''):'<div class="empty-copy">Nothing logged for this day.</div>';$$('[data-del-food]').forEach(b=>b.onclick=()=>{state.foods=state.foods.filter(x=>x.id!==b.dataset.delFood);save();renderAll()})}
$('#addCustomFood').onclick=()=>{const name=$('#customName').value.trim();if(!name)return toast('Enter a food name');state.foods.push({id:id(),date:$('#foodDate').value,meal:$('#foodMeal').value,name,serving:$('#customServing').value||'custom',cal:n($('#customCal').value),protein:n($('#customProtein').value),carbs:n($('#customCarbs').value),fat:n($('#customFat').value),fibre:n($('#customFibre').value),sugar:n($('#customSugar').value),sodium:n($('#customSodium').value),created:Date.now()});['customName','customServing','customCal','customProtein','customCarbs','customFat','customFibre','customSugar','customSodium'].forEach(x=>$('#'+x).value='');save();renderAll();toast('Custom food added')};
function renderBody(){const arr=[...state.body].sort((a,b)=>b.date.localeCompare(a.date));$('#bodyHistory').innerHTML=arr.length?arr.map(x=>`<div class="history-row"><div><strong>${x.weight??'—'} kg</strong><div class="row-meta">${x.date}${x.fat?` · Fat ${x.fat}%`:''}${x.muscle?` · Muscle ${x.muscle} kg`:''}${x.water?` · Water ${x.water}%`:''}</div></div><button class="delete-mini" data-del-body="${x.id}">×</button></div>`).join(''):'<div class="empty-copy">No measurements yet.</div>';$$('[data-del-body]').forEach(b=>b.onclick=()=>{state.body=state.body.filter(x=>x.id!==b.dataset.delBody);save();renderAll()})}
$('#saveBody').onclick=()=>{const x={id:id(),date:$('#bodyDate').value,weight:n($('#bodyWeight').value)||null,fat:n($('#bodyFat').value)||null,muscle:n($('#bodyMuscle').value)||null,water:n($('#bodyWater').value)||null,visceral:n($('#bodyVisceral').value)||null,bone:n($('#bodyBone').value)||null,metabolicAge:n($('#bodyMetabolicAge').value)||null,waist:n($('#bodyWaist').value)||null,chest:n($('#bodyChest').value)||null};state.body=state.body.filter(y=>y.date!==x.date);state.body.push(x);if(x.weight)state.profile.weight=x.weight;save();renderAll();toast('Measurement saved')};
function renderProfile(){const p=state.profile;$('#profileName').value=p.name;$('#profileSex').value=p.sex;$('#profileAge').value=p.age;$('#profileHeight').value=p.height;$('#profileWeight').value=p.weight;$('#profileActivity').value=String(p.activity);$('#profileGoal').value=String(p.goal);$('#targetProtein').value=p.protein;$('#targetFibre').value=p.fibre;$('#timeBreakfast').value=p.times.Breakfast;$('#timeLunch').value=p.times.Lunch;$('#timeDinner').value=p.times.Dinner;$('#timeSnack').value=p.times.Snack}
$('#saveProfile').onclick=()=>{state.profile={name:$('#profileName').value||'Me',sex:$('#profileSex').value,age:n($('#profileAge').value),height:n($('#profileHeight').value),weight:n($('#profileWeight').value),activity:n($('#profileActivity').value),goal:n($('#profileGoal').value),protein:n($('#targetProtein').value),fibre:n($('#targetFibre').value),times:{Breakfast:$('#timeBreakfast').value,Lunch:$('#timeLunch').value,Dinner:$('#timeDinner').value,Snack:$('#timeSnack').value}};save();renderAll();toast('Profile saved')};
function drawChart(cid,labels,vals,target){const c=$('#'+cid),ctx=c.getContext('2d'),DPR=window.devicePixelRatio||1,w=c.clientWidth||340,h=220;c.width=w*DPR;c.height=h*DPR;ctx.scale(DPR,DPR);ctx.clearRect(0,0,w,h);const pad={l:42,r:10,t:12,b:28},W=w-pad.l-pad.r,H=h-pad.t-pad.b,good=vals.filter(v=>v!=null);let min=good.length?Math.min(...good):0,max=good.length?Math.max(...good):1;if(target!=null){min=Math.min(min,target);max=Math.max(max,target)}if(max===min)max=min+1;const extra=(max-min)*.12||1;min=Math.max(0,min-extra);max+=extra;const X=i=>pad.l+(labels.length<2?W/2:i*W/(labels.length-1)),Y=v=>pad.t+H-(v-min)/(max-min)*H;ctx.font='11px -apple-system,system-ui';ctx.fillStyle='#64748b';ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;for(let i=0;i<4;i++){const yy=pad.t+i*H/3;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText(String(r(max-(max-min)*i/3,1)),4,yy+4)}if(target!=null){ctx.strokeStyle='#f59e0b';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(pad.l,Y(target));ctx.lineTo(w-pad.r,Y(target));ctx.stroke();ctx.setLineDash([])}ctx.strokeStyle='#0f766e';ctx.lineWidth=2.6;ctx.beginPath();let started=false;vals.forEach((v,i)=>{if(v==null)return;const x=X(i),y=Y(v);started?(ctx.lineTo(x,y)):(ctx.moveTo(x,y),started=true)});ctx.stroke();ctx.fillStyle='#0f766e';vals.forEach((v,i)=>{if(v==null)return;ctx.beginPath();ctx.arc(X(i),Y(v),3,0,Math.PI*2);ctx.fill()});if(labels.length){ctx.fillStyle='#64748b';ctx.fillText(labels[0].slice(5),pad.l,h-8);const last=labels.at(-1).slice(5);ctx.fillText(last,w-pad.r-34,h-8)}}
function renderTrends(){const days=n($('#trendRange').value,30),labels=[];for(let i=days-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);labels.push(dateISO(d))}const g=targets(),cals=labels.map(d=>{const v=totals(d).cal;return v?Math.round(v):null}),pro=labels.map(d=>{const v=totals(d).protein;return v?r(v,1):null});const bm=Object.fromEntries(state.body.map(x=>[x.date,x]));const wei=labels.map(d=>bm[d]?.weight??null),fat=labels.map(d=>bm[d]?.fat??null);drawChart('chartCalories',labels,cals,g.cal);drawChart('chartProtein',labels,pro,g.protein);drawChart('chartWeight',labels,wei,null);drawChart('chartFat',labels,fat,null);const avg=a=>{const x=a.filter(v=>v!=null);return x.length?r(x.reduce((s,v)=>s+v,0)/x.length,1):null};$('#avgCalories').textContent=avg(cals)!=null?`Avg ${avg(cals)} kcal`:'';$('#avgProtein').textContent=avg(pro)!=null?`Avg ${avg(pro)} g`:'';const change=a=>{const x=a.filter(v=>v!=null);return x.length>1?r(x.at(-1)-x[0],1):null};const wc=change(wei),fc=change(fat);$('#weightChange').textContent=wc!=null?`${wc>0?'+':''}${wc} kg`:'';$('#fatChange').textContent=fc!=null?`${fc>0?'+':''}${fc}%`:''}
$('#trendRange').onchange=renderTrends;
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nutritrack-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);state={...defaults(),...x};save();renderAll();toast('Backup imported')}catch{toast('Invalid backup file')}};rd.readAsText(f)};$('#eraseData').onclick=()=>{if(confirm('Erase all NutriTrack data from this device?')){state=defaults();save();renderAll();toast('All data erased')}};
function shiftDay(delta){const d=new Date(selectedDate()+'T12:00:00');d.setDate(d.getDate()+delta);$('#selectedDate').value=dateISO(d);renderHome()}$('#prevDay').onclick=()=>shiftDay(-1);$('#nextDay').onclick=()=>shiftDay(1);$('#selectedDate').onchange=renderHome;$('#foodDate').onchange=renderFoodLog;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true}else navigate('settings')};
function renderAll(){renderHome();renderFoodResults();renderFoodLog();renderBody();renderProfile();if($('#page-trends').classList.contains('active'))renderTrends()}
function init(){const t=today();$('#selectedDate').value=t;$('#foodDate').value=t;$('#bodyDate').value=t;renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init();
